= Parameters

Because this component depends on the component https://hub.syn.tools/appuio-cloud-reporting/references/parameters.html[appuio-cloud-reporting], some parameters are taken from that component and are not individually configurable in this component.
In particular:

* https://hub.syn.tools/appuio-cloud-reporting/references/parameters.html#_namespace[namespace]
* https://hub.syn.tools/appuio-cloud-reporting/references/parameters.html#_database[database]

The following list includes only parameters of this component.
The parent key for all of them is `cloudscale_metrics_collector`.

See xref:how-tos/installation.adoc[Installation] for a full example.

== `images`

[horizontal]
type:: dictionary
default:: https://github.com/vshn/cloudscale-metrics-collector/blob/master/component/class/defaults.yml[See `class/defaults.yml].

Dictionary containing the container images used by this component.


== `secrets.cloudscale.stringData.token`

[horizontal]
type:: string
default:: Required.

The cloudscale API token.

You need to get the token from the https://control.cloudscale.ch[Cloudscale Control Panel].
You need to select the correct Project (token is limited to one project), choose "API Tokens" in the menu and generate a new one.
